{{- if and .Values.features.uaa.native .Values.features.ingress.enabled }}
---
apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: uaa
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # Inject some annotations if they don't exist in the annotations provided during deployment.
    {{- $annotations := deepCopy .Values.features.ingress.annotations }}
    {{- $annotations = dict "kubernetes.io/ingress.class" "nginx" | merge $annotations }}
    {{- $_ := set $annotations "nginx.ingress.kubernetes.io/secure-backends" "false" }}
    {{- $_ := set $annotations "nginx.ingress.kubernetes.io/backend-protocol" "HTTP" }}
    {{- $annotations = dict "nginx.ingress.kubernetes.io/ssl-redirect" "false" | merge $annotations }}
    {{- $annotations = dict "nginx.ingress.kubernetes.io/proxy-body-size" "64m" | merge $annotations }}
    {{- toYaml $annotations | indent 4 }}
  labels:
    {{- $labels := dict }}
    {{- with .Values.features.ingress.labels }}
    {{- $labels = deepCopy . }}
    {{- end }}
    {{- $labels = dict "app.kubernetes.io/component" "ingress" | merge $labels }}
    {{- $labels = dict "app.kubernetes.io/instance" .Release.Name | merge $labels }}
    {{- $labels = dict "app.kubernetes.io/managed-by" .Release.Service | merge $labels }}
    {{- $labels = default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | dict "app.kubernetes.io/name" .Release.Service | merge $labels }}
    {{- $labels = default .Chart.Version .Chart.AppVersion | dict "app.kubernetes.io/version" | merge $labels }}
    {{- $labels = printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | dict "helm.sh/chart" | merge $labels }}
    {{- toYaml .Values.features.ingress.labels | indent 4 }}
spec:
  {{- $hostnames := list }}
  {{- range list "uaa" "*.uaa" "login" "*.login" }}
    {{- $hostnames = printf "%s.%s" . $.Values.system_domain | append $hostnames }}
  {{- end }}
  tls:
  - secretName: {{ .Release.Name }}-ingress-tls
    hosts:
    {{- range $hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
  {{- range $hostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: uaa
          servicePort: 8080
  {{- end }}

{{- end }}
