---
apiVersion: v1
kind: Service
metadata:
  name: uaa
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: uaa
    port: 8080
    protocol: TCP
    targetPort: http-uaa
  selector:
    app: uaa
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: ingress.kube-system.svc
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-ingress-controller
  type: ClusterIP
