system_domain: ~
deployment_name: kubecf

# Set or override job properties. The first level of the map is the instance group name. The second
# level of the map is the job name. E.g.:
#  properties:
#    adapter:
#      adapter:
#        scalablesyslog:
#          adapter:
#            logs:
#              addr: kubecf-log-api:8082
properties: {}

# The the storage class to be used for the instance groups that need it (e.g. bits, database and singleton-blobstore)
# If it's not set, the default storage class will be used.
kube:
  storage_class: ~

releases:
  # The defaults for all releases, where we do not otherwise override them.
  defaults:
    url: docker.io/cfcontainerization
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_362.g9610e90b
  bits-service:
    stemcell:
      version: 36.g03b4653-30.80-7.0.0_348.gc8fb3864
  capi:
    version: 1.83.0
    stemcell:
      version: 36.g03b4653-30.80-7.0.0_360.g0ec8d681
  cf-acceptance-tests:
    stemcell:
      version: 36.g03b4653-30.80-7.0.0_367.g6b06e343
  cf-mysql:
    version: 36.19.0
    stemcell:
      version: 36.g03b4653-30.80-7.0.0_360.g0ec8d681
  eirini:
    stemcell:
      version: 36.g03b4653-30.80-7.0.0_360.g0ec8d681

sizing:
  HA: false

# Service is only valid to set an external endpoint for the router if features.ingress.enabled is
# false.
service:
  type: LoadBalancer
  externalIPs: []
  clusterIP: ~

features:
  eirini:
    enabled: false
    registry:
      service:
        nodePort: 32123
  ingress:
    enabled: false
    tls:
      crt: ~
      key: ~
    annotations: {}
    labels: {}
  # TODO: suse_buildpacks should be default to true after the opensuse-stemcell-based images are
  # published to docker.io.
  suse_buildpacks:
    enabled: false

operations:
  # A list of configmap names that should be applied to the BOSH manifest.
  custom: []

k8s-host-url: ""
k8s-service-token: ""
k8s-service-username: ""
k8s-node-ca: ""
