{{- $root := . -}}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: {{ .Values.deployment_name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
spec:
  manifest:
    name: cf-deployment
    type: configmap
  ops:
{{- range $path, $bytes := .Files.Glob "assets/operations/instance_groups/*" }}
  - name: {{ include "kubecf.ops-name" $path }}
    type: configmap
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/temporary/*" }}
  - name: {{ include "kubecf.ops-name" $path }}
    type: configmap
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/*" }}
  - name: {{ include "kubecf.ops-name" $path }}
    type: configmap
{{- end }}
{{/* Find the list of features available */}}
{{- $features := dict }}
{{- range $featureFile, $_ := .Files.Glob "assets/operations/features/**" }}
{{- $_ := set $features (index (splitList "/" $featureFile) 3) true }}
{{- end }}
{{/* Enable feature ops if the feature flag is set */}}
{{- range $featureName := keys $features | sortAlpha }}
{{- $featureFlag := regexSplit "_" $featureName 2 | last }}
{{- if index $root.Values.features $featureFlag "enabled" }}
  - name: {{ include "kubecf.ops-name" (printf "feature-%s" $featureFlag) }}
    type: configmap
{{- end }}
{{- end }}
{{- if not .Values.sizing.HA }}
  - name: ops-single-availability
    type: configmap
{{- end }}
{{- range $_, $ops := .Values.operations.custom }}
  - name: {{ $ops | quote }}
    type: configmap
{{- end }}
  - name: user-provided-properties
    type: configmap
