# This template creates a ConfigMap for each ops file under assets/operations.
{{- define "kubecf.ops" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubecf.ops-name" .Path }}
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Root.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Root.Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" .Root }}
    app.kubernetes.io/version: {{ default .Root.Chart.Version .Root.Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" .Root }}
data:
  ops: |-
    {{- tpl (toString .Data) .Root | nindent 4 -}}
{{- end -}}

{{- $root := . -}}

{{/* Find the list of features available */}}
{{- $features := dict }}
{{- range $featureFile, $bytes := .Files.Glob "assets/operations/features/**" }}
{{- $featureName := index (splitList "/" $featureFile) 3 }}
{{- $featureData := index $features $featureName | default "" }}
{{- $_ := set $features $featureName (printf "%s\n%s" $featureData (toString $bytes)) }}
{{- end }}
{{/* Dump out the feature ops files */}}
{{- range $featureName, $featureData := $features }}
{{- $featureFlag := regexSplit "_" $featureName 2 | last }}
{{- if index $root.Values.features $featureFlag "enabled" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" (printf "feature-%s" $featureFlag) "Data" $featureData) }}
{{- end }}
{{- end }}

{{- range $path, $bytes := .Files.Glob "assets/operations/instance_groups/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path "Data" $bytes) }}
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/temporary/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path "Data" $bytes) }}
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path "Data" $bytes) }}
{{- end }}
