---
{{- if .Values.features.credhub.enabled }}
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/quarks?
  value:
    ports:
    - name: credhub
      protocol: TCP
      internal: &credhub_tls_port 8844
    run:
      healthcheck:
        credhub:
          readiness:
            httpGet:
              port: 8845
              path: /health

- type: replace
  path: /instance_groups/name=credhub/jobs/-
  value:
    name: route_registrar
    release: routing
    properties:
      route_registrar:
        routes:
        - name: credhub
          tls_port: *credhub_tls_port
          server_cert_domain_san: credhub.service.cf.internal
          registration_interval: 10s
          tags:
            component: credhub
          uris:
          - credhub.((system_domain))

- type: replace
  path: /instance_groups/name=credhub/jobs/-
  value:
    name: credhub-setup
    release: scf-helper
    properties:
      credhub_setup:
        oauth_secret:
          ((credhub_setup_client_secret))
      quarks:
        envs:
        - name: CF_API
          value: https://cloud-controller-ng.service.cf.internal:9024
        - name: CF_CA
          value: ((cc_tls.ca))
        - name: CF_USERNAME
          value: credhub_setup_client
        - name: CF_PASSWORD
          value: ((credhub_setup_client_secret))
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_PORTS
          value: *credhub_tls_port

- type: replace
  path: /instance_groups/name=uaa/jobs/-
  value:
    name: credhub-setup
    release: scf-helper
    properties:
      credhub_setup:
        oauth_secret:
          ((credhub_setup_client_secret))
      quarks:
        envs:
        - name: CF_API
          value: https://cloud-controller-ng.service.cf.internal:9024
        - name: CF_CA
          value: ((cc_tls.ca))
        - name: CF_USERNAME
          value: credhub_setup_client
        - name: CF_PASSWORD
          value: ((credhub_setup_client_secret))
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_PORTS
          value: "8443"

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/credhub_setup_client?
  value:
    authorities: cloud_controller.admin
    authorized-grant-types: client_credentials
    secret: ((credhub_setup_client_secret))

- type: replace
  path: /variables/name=credhub_setup_client_secret?
  value:
    name: credhub_setup_client_secret
    type: password
{{- end }}

{{- if not .Values.features.credhub.enabled }}
# Remove directly from the cf-deployment.yml YAML file.
- path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=credhub.service.cf.internal?
  type: remove
- path: /instance_groups/name=database/jobs/name=pxc-mysql/properties/seeded_databases/name=credhub?
  type: remove
- path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cc_service_key_client?
  type: remove
- path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/credhub_admin_client?
  type: remove
- path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/credhub_api?
  type: remove
- path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs3-rootfs-setup/properties/cflinuxfs3-rootfs/trusted_certs/1
  type: remove
- path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/trusted_ca_certificates/1
  type: remove
- path: /instance_groups/name=credhub?
  type: remove
- path: /variables/name=credhub_encryption_password?
  type: remove
- path: /variables/name=credhub_admin_client_secret?
  type: remove
- path: /variables/name=credhub_database_password?
  type: remove
- path: /variables/name=credhub_ca?
  type: remove
- path: /variables/name=credhub_tls?
  type: remove
- path: /releases/name=credhub?
  type: remove
{{- end }}
